### ISSUE TITLE
Conda installation fails on example

### ISSUE THREAD

**Issue by rsdefever** [cdsgroup/resp#17]
It appears that the `conda` installation of `resp` may be out of date. I tried installing `psi4` and `resp` into a new conda environment as follows:

```
 conda create --name resp psi4 resp -c psi4
```

However, when I try to run the example in `example1.py`, I get the following error:

```
Traceback (most recent call last):
  File "example1.py", line 21, in <module>
    charges1 = resp.resp([mol], options)
  File "/Users/user/anaconda3/envs/resp-fail/lib/python3.7/site-packages/resp/driver.py", line 61, in resp
    options = {k.upper(): v for k, v in sorted(options_list[0].items())}
KeyError: 0
```

Installing `psi4` from conda and `resp` from source works just fine.

**Comment by loriab** [comment]
Unless you knowingly prefer psi4 v1.3, please give your `conda create` command a try with `-c psi4/label/dev` instead of `-c psi4`. That combination I know was working for the test suite `python -c "import resp, sys; sys.exit(resp.test('long'))"` as of last week.

Sounds like I should check up on compatibility with both master and v1.3 and whether those examples get tested regularly. But the above should get you working for now

**Comment by rsdefever** [comment]
Apologies; I did a poor job of describing the issue and I didn't fully understand what was happening.

It appears that the version of `resp` distributed on `conda` is `0.8.1`. The GH version is currently at `1.0`. I was using the GH `example1.py` code to get my feet on the ground. However, there were some changes between `0.8.1` and `1.0` that cause the current version of the example to be incompatible with `0.8.1` and cause the above-reported error. 

Your instructions

>> python -c "import resp, sys; sys.exit(resp.test('long'))"

indeed work with `-c psi4/label/dev`. 

Sorry for the confusion.

**Comment by loriab** [comment]
No problem. I definitely need to rebuild the conda package so thanks for the alert. Glad you've got a setup working for now.

**Comment by rsdefever** [comment]
I'll let you decide if you prefer to close out the issue or leave it open as a reminder for yourself. Thanks again.

**Comment by loriab** [comment]
I did repackage resp a few weeks ago at the 1.0 version, so closing this out. Please reopen or start a new issue if problems continue.
