### ISSUE TITLE
RESPs from wavefunctions

### ISSUE THREAD

**Issue by mireklzicar** [cdsgroup/resp#21]
Let's say I have a psi4 wfn files: wfn = psi4.core.Wavefunction.from_file("mol.wfn") with all the relevant matrices. Is it possible to obtain RESP charges from it? Using psi4 cubeprop I may get the grid, but I have no clue if it is possible to reuse it in concert with this repository.
a) is it possible? b) if yes what parts of the code in this repo may I use for that? (I understand that it accepts currently only mol or smiles, but it still needs to infer the charges from psi4 in the background)

**Comment by alenaizan** [comment]
First, you should not use cubeprop. The RESP grid is not rectangular but is based on the so-called Connolly surface. You can use the function `vdw_surface` to generate the grid.

Assuming you have the correct grid, you can use the Psi4 function `oeprop` to calculate the electrostatic potential. See the details here: https://psicode.org/psi4manual/master/oeprop.html
```
oeprop(wfn, 'GRID_ESP')
```

Finally, you can use grid and electrostatic potential values as inputs to the RESP program. You can use options `grid` and `esp` to set the path to your grid and ESP values. See for example how I do it here for the stage 2 fitting: https://github.com/cdsgroup/resp/blob/master/examples/example1.py

Let me know if this solves your issue.

**Comment by mireklzicar** [comment]
Thanks, for anyone doing the same here is the code snippet I used: https://gist.github.com/mireklzicar/decce3622353a5c1ffdefd50f0b0133b
Is it correct?

**Comment by alenaizan** [comment]
I think this should work, but you need to change the coordinates in line 16 to Angstrom. The values of `wfn_mol.geometry()` are in Bohr.

**Comment by mireklzicar** [comment]
That is done on the line 13 using wfn_mol.set_units(psi4.core.Angstrom), is it?

**Comment by alenaizan** [comment]
I think `wfn_mol.geometry()` always return the values in Bohr.

**Comment by mireklzicar** [comment]
Oh, yes, now it works. I have updated the gist. Thanks.
